remote_theme: "mmistakes/minimal-mistakes@4.19.3"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "dark"

locale: "en-US"

repository: "jacobranson/jacobranson.github.io"

name: "Jacob Ranson"
title: "Jacob Ranson"
title_separator: "|"
description: "My personal website."

include: ["_pages"]

main:
  - title: "About Me"
    url: /about/
