remote_theme: "mmistakes/minimal-mistakes@4.19.3"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "dark"

locale: "en-US"

repository: "jacobranson/jacobranson.github.io"

name: "Jacob Ranson"
title: "Jacob Ranson"
title_separator: "|"
description: "My personal website."
search: true

permalink: /:categories/:title/
paginate: 5
paginate_path: /blog/page:num
timezone: America/New_York

include:
  - _pages

author:
  name   : "Jacob Ranson"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I am a full-stack web developer with aspirations to move into the game development field. I have extensive experience with Angular frontend web development, and am currently employed by Randstad USA working as an intern for Vanguard."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/jacobranson"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-square"
      url: "https://www.linkedin.com/in/jacobrileighranson/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/jacobranson"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-square"
      url: "https://www.linkedin.com/in/jacobrileighranson/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
